sudo: true
dist: trusty
language: node_js
node_js:
  - stable
cache: npm
notifications:
  email:
    on_failure: change
    on_success: change
ssh_known_hosts: 206.189.169.212
branches:
  only:
    - master
env:
  global:
    - REMOTE_APP_DIR=~/builds
    - REMOTE_USER=deploy
    - REMOTE_HOST=206.189.169.212
    - PORT=3000
before_install:
  - openssl aes-256-cbc -K $encrypted_886e1d2bd29d_key -iv $encrypted_886e1d2bd29d_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $REMOTE_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@$REMOTE_HOST pwd
  - npm install -g npm
  - chmod +x .travis/deploy.sh
install:
  - npm install
before_script:
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
#  - chmod 600 deploy && cp deploy ~/.ssh/id_rsa
script:
  - npm run test:coverage
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
