language: node_js
node_js:
- stable
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 206.189.169.212
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/upword.ly/
  - REMOTEUSER=travis
  - REMOTEHOST=206.189.169.212
  - PORT=8080
beforeinstall:
- npm install -g
install:
- openssl aes-256-cbc -K $encrypted_886e1d2bd29d_key -iv $encrypted_886e1d2bd29d_iv
  -in deploy.enc -out deploy -d
- npm install --only=dev
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- npm run build
after_success:
- ".travis/deploy.sh"

