sudo: true
dist: trusty
language: node_js
node_js:
  - stable
cache: npm
notifications:
  email:
    on_failure: change
    on_success: change
ssh_known_hosts:
  - 206.189.169.212
apt_packages:
  - sshpass
branches:
  only:
    - master
env:
  global:
    - REMOTE_APP_DIR=~/upwordly-build
    - REMOTE_USER=deploy
    - REMOTE_HOST=206.189.169.212
    - PORT=3000
before_install:
  - openssl aes-256-cbc -K $encrypted_886e1d2bd29d_key -iv $encrypted_886e1d2bd29d_iv -in deploy.enc -out deploy -d
  - npm install -g npm
  - chmod +x .travis/deploy.sh
  - chmod +x .travis/untar.sh
install:
  - npm install
before_script:
  - chmod 600 deploy && cp deploy ~/.ssh/id_rsa
script:
  - npm run test:coverage
after_success:
  - npm run build
  - chmod 600 deploy && cp deploy ~/.ssh/id_rsa
  - set x
  - export SSHPASS=$PASSKEY
  - tar -czf package.tgz ./
  - scp package.tgz $REMOTE_USER@$REMOTE_HOST:$REMOTE_APP_DIR
#  - sshpass -e ssh $REMOTE_USER@$REMOTE_HOST $REMOTE_APP_DIR/.travis/deploy.sh

#                - ls
#
#                - sshpass -p $PASSKEY scp -o StrictHostKeyChecking=no package.tgz $REMOTE_USER@$REMOTE_HOST:$REMOTE_APP_DIR
#                - sshpass -p $PASSKEY ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST
#                - export NODE_ENV=production
#                - cd /var/www/upword.ly
#                - tar -zxvf package.tgz -C .
#                - mv build/package.json .
#                - npm install
#                - npm start

